version: '0.2'

phases:
  install:
    commands:
      - 'yarn'
  build: 
    commands: 
      - 'yarn build:profile --production'

artifacts: 
  base-directory: 'packages/profile/dist'
  files: 
    - '*'