version: '0.2'

phases:
  install:
    commands:
      - 'npm install'
  build: 
    commands: 
      - 'npm run build:profile --production'

artifacts: 
  base-directory: 'packages/profile'
  files: 
    - '*'