version: '0.2'

phases:
  install:
    commands:
      - 'npm install'
  build: 
    commands: 
      - 'npm run build'
      - 'npm run cdk synth -- -o dist'
      - 'ls'

artifacts: 
  base-directory: 'cdk.out'
  files: 
    - 'ModuleFederationsPocStack.template.json'