version: '0.2'

phases:
  install:
    commands:
      - 'yarn'
  build: 
    commands: 
      - 'yarn compile'
      - 'yarn cdk synth -- -o dist'

artifacts: 
  base-directory: 'dist'
  files: 
    - 'ModuleFederationsPocStack.template.json'