version: '0.2'

phases:
  install:
    commands:
      - 'npm install'
  build: 
    commands: 
      - 'npm run compile'
      - 'npm run cdk synth -- -o dist'

artifacts: 
  base-directory: 'dist'
  files: 
    - 'ModuleFederationsPocStack.template.json'